// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_token.sql

package database

import (
	"context"
	"database/sql"
)

const updateToken = `-- name: UpdateToken :exec
UPDATE refresh_tokens
SET revoked_at = $2, updated_at = $2
WHERE refresh_tokens.token = $1
`

type UpdateTokenParams struct {
	Token     string
	RevokedAt sql.NullTime
}

func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateToken, arg.Token, arg.RevokedAt)
	return err
}
