// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_user_red.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateUserRed = `-- name: UpdateUserRed :one
UPDATE users
SET is_chirpy_red = $2, updated_at = $3
WHERE id = $1
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type UpdateUserRedParams struct {
	ID          uuid.UUID
	IsChirpyRed bool
	UpdatedAt   time.Time
}

func (q *Queries) UpdateUserRed(ctx context.Context, arg UpdateUserRedParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserRed, arg.ID, arg.IsChirpyRed, arg.UpdatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
